source 'https://cdn.cocoapods.org/'
source 'https://github.com/blairBai/YFSpecs.git'

install! 'cocoapods', :deterministic_uuids => false

use_frameworks!

platform :ios, '9.0'

target 'TYCustomScrollView_Example' do
  pod 'TYCustomScrollView', :path => '../'

  pod 'LookinServer', '1.0.0', :configurations => ['Debug']
  
  target 'TYCustomScrollView_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
